CREATE TABLE `apply_contact_list` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '自增主键ID',
  `seq` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '序列号',
  `user_id` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '用户ID',
  `name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '用户名',
  `sex` tinyint(4) DEFAULT NULL COMMENT '性别：1-男，2-女',
  `avatar` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '头像URL',
  `corp_id` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '企业ID',
  `unionid` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'UnionID',
  `type` tinyint(4) DEFAULT NULL COMMENT '类型',
  `flag` tinyint(4) DEFAULT NULL COMMENT '标志',
  `create_time` bigint(20) DEFAULT NULL COMMENT '创建时间戳',
  `update_time` bigint(20) DEFAULT NULL COMMENT '更新时间戳',
  `corp_name` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '企业名称',
  `corp_short_name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '企业简称',
  `source_type` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '来源类型',
  `source_user_id` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '来源用户ID',
  `source_room_id` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '来源房间ID',
  `apply_reason` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '申请理由',
  `add_time` bigint(20) DEFAULT NULL COMMENT '添加时间',
  `extend_info_desc` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '扩展信息-描述',
  `extend_info_remark` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '扩展信息-备注',
  `extend_info_company_remark` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '扩展信息-企业备注',
  `extend_info_remark_time` int(11) DEFAULT NULL COMMENT '扩展信息-备注时间',
  `extend_info_remark_url` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '扩展信息-备注URL',
  `create_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_corp_id` (`corp_id`),
  KEY `idx_unionid` (`unionid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='申请好友列表';