CREATE TABLE `juhebot_message_callback` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `guid` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '用户ID',
  `notify_type` int(11) NOT NULL COMMENT '通知类型',
  `seq` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '序列号',
  `msg_id` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '消息ID',
  `appinfo` text COLLATE utf8mb4_unicode_ci COMMENT '应用信息',
  `sender` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '发送者ID',
  `receiver` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '接收者ID',
  `room_id` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT '0' COMMENT '群聊ID',
  `send_time` int(11) DEFAULT NULL COMMENT '发送时间戳',
  `sender_name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '发送者名称',
  `content_type` int(11) DEFAULT NULL COMMENT '内容类型',
  `refer_id` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT '0' COMMENT '引用ID',
  `flag` bigint(20) DEFAULT NULL COMMENT '标志位',
  `content` text COLLATE utf8mb4_unicode_ci COMMENT '消息内容',
  `at_list` json DEFAULT NULL COMMENT '@成员列表',
  `quote_content` text COLLATE utf8mb4_unicode_ci COMMENT '引用内容',
  `quote_appinfo` text COLLATE utf8mb4_unicode_ci COMMENT '引用应用信息',
  `send_flag` int(11) DEFAULT '1' COMMENT '发送标志',
  `msg_type` int(11) DEFAULT NULL COMMENT '消息类型',
  `raw_data` json DEFAULT NULL COMMENT '原始数据',
  `is_processed` tinyint(1) DEFAULT '0' COMMENT '是否已处理',
  `processed_at` datetime DEFAULT NULL COMMENT '处理时间',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_guid` (`guid`),
  KEY `idx_notify_type` (`notify_type`),
  KEY `idx_sendtime` (`send_time`),
  KEY `idx_roomid` (`room_id`),
  KEY `idx_sender` (`sender`),
  KEY `idx_is_processed` (`is_processed`)
) ENGINE=InnoDB AUTO_INCREMENT=61 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Juhebot消息回调表';